### ISSUE TITLE
Discussion: feedback on json files

### ISSUE THREAD

**Issue by Jackymancs4** [Davis24/video-game-text-dataset#2]
Among other things, I was trying to create a JSON schema (https://json-schema.org/) to ease consumption and validation of the files.

While quite easy to do, It had me have some consideration:

1. I think the `codexes `object somewhat violates the semantics of json objects, and should be better as a json list. I can discuss the reasoning and benefits of this approach if you like, but anyway I suggest to modify it from 
```json
{ "codexes" : { "$id" : {"title": $title}}}
```
to 
```json
{ "codexes" : [ {"id": $id, "title": $title} ]}
```

2. I suggest to add a `series_title `at the same level of `game_title`
Useful if I'm working on a single file, outside the dataset in general.
E.g crysis folder

3. In the codex object I suggest to add a `type` string property to distinguish the in game type of text.
For example Dishonored has recordings and books. The book provided by the library of codexes make the distintion as named sections.

4. The `authors` field (because it's plural) should always be a list, even when it as a single name in it.
```json
{ "authors": "Dominic H. Lockhart" }
```
to 
```json
{ "authors": ["Dominic H. Lockhart"] }
```

Those are of course just my opinions.
If you agree and would like some help in modifying the dataset, I can provide one or multiple PRs in the following days.

Thank you.

**Comment by Davis24** [comment]
1. Agreed, changed and will be uploaded with next commit.
2. Agreed, changed and will be uploaded with next commit.
3. Agreed, _however_ I do not have this information available. The backend database doesn't include a 'type' attribute for codex table. I happen to know what types exist due to having had to ensure I had all the entries collected. I'll put this in a backlog of modify the database to include a type and retroactively fixing it. But unfortunately for now no 'type' attribute will be available.
4. Agreed, changed and will be uploaded with next commit.

**Comment by Davis24** [comment]
I've gone ahead and uploaded the .json with the changes. I'll open (3) in a separate issue to eventually be addressed but no ETA. Thanks for all your feedback please feel free to open up more issues if you notice something.
